name: onmyoji_wiki
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  rxdart: ^0.27.7
  flutter_simple_dependency_injection: ^2.0.0
  flutter_screenutil: ^5.6.0
  path_provider: ^2.0.11
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/SP/kiyohime/
    - assets/SP/enma/
    - assets/SP/momiji/
    - assets/SP/orochi/
    - assets/SSR/jinkougyou/
    - assets/SR/kairaishi/
    - assets/R/kappa/
    - assets/N/parasite/
